CREATE USER 'infom141'@'localhost' IDENTIFIED BY 'cs121';
GRANT ALL PRIVILEGES ON *.* TO 'infom141'@'localhost'  WITH GRANT OPTION;
CREATE USER 'infom141'@'%' IDENTIFIED BY 'cs121';
GRANT ALL PRIVILEGES ON *.* TO 'infom141'@'%' WITH GRANT OPTION;